# Generated by Django 3.0.5 on 2020-11-07 20:35

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coll',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
    ]
