# Generated by Django 3.0.5 on 2020-11-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
