# Generated by Django 3.0.5 on 2020-11-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coll',
            name='ids',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
